apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: scott-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: scott-petclinic
spec:
  params:
    - name: run-image
      value: ghcr.io/vrabbi/scott-petclinic
    - name: tekton-pipeline-name
      value: developer-defined-tekton-pipeline
  source:
    git:
      url: https://github.com/vrabbi/scott-petclinic
      ref:
        branch: main
